opendebate.processTimeline({
  "iface": "timeline", 
  "entries": [
    {
      "city": "Martinez", 
      "first_name": "Katherine", 
      "last_name": "Myskowski", 
      "user_id": 1744878, 
      "submission": "Will you vote to end tax loopholes for the rich, big business subsides, overseas corporate tax loopholes, wasteful wars, foreign country subsides, quality health care for all, good safe food for all, clean air, clean energy, clean safe drinking water, useful education and job opportunities for all hard working citizens that can achieve these levels and deserve it, gun control, to end wall street fraud and corruption.", 
      "district": "CA_05", 
      "created": "2013-08-09T01:33:03", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 37.9913, 
      "x": -122.164, 
      "id": 16254719, 
      "question_id": "16203215"
    }, 
    {
      "city": "Waukesha", 
      "first_name": "Jean", 
      "last_name": "Hartje", 
      "user_id": 660781, 
      "submission": "Will you vote to end tax loopholes for the rich, big business subsides, overseas corporate tax loopholes, wasteful wars, foreign country subsides, quality health care for all, good safe food for all, clean air, clean energy, clean safe drinking water, useful education and job opportunities for all hard working citizens that can achieve these levels and deserve it, gun control, to end wall street fraud and corruption.", 
      "district": "WI_05", 
      "created": "2013-08-09T01:33:03", 
      "state": "WI", 
      "iface": "timeline_vote", 
      "y": 43.0162, 
      "x": -88.2679, 
      "id": 16254720, 
      "question_id": "16203215"
    }, 
    {
      "city": "Crossett", 
      "first_name": "Brenda ", 
      "last_name": "Castleberry", 
      "user_id": 372898, 
      "submission": "How do you propose stopping the GOPs continued assault on women's reproductive rights?", 
      "district": "AR_04", 
      "created": "2013-08-09T01:33:02", 
      "state": "AR", 
      "iface": "timeline_vote", 
      "y": 33.1291, 
      "x": -91.9607, 
      "id": 16254717, 
      "question_id": "16205884"
    }, 
    {
      "city": "Pacifica", 
      "first_name": "Dave", 
      "last_name": "Steenhoven", 
      "user_id": 41422, 
      "submission": "Do you support the legalization of marijuana (which should be taxed & regulated like alcohol or tobacco)? If so, would you allow the release of nonviolent offenders from prison?", 
      "district": "CA_14", 
      "created": "2013-08-09T01:33:02", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 37.6023, 
      "x": -122.486, 
      "id": 16254718, 
      "question_id": "16172722"
    }, 
    {
      "city": "Sacramento", 
      "first_name": "Wendy", 
      "last_name": "Wein", 
      "user_id": 194354, 
      "submission": "What will you do to ensure that all Americans have access to the voting booth and what will you do to get money out of our elections so that we all have an equal voice?", 
      "district": "CA_06", 
      "created": "2013-08-09T01:33:01", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 38.4983, 
      "x": -121.534, 
      "id": 16254715, 
      "question_id": "16205834"
    }, 
    {
      "city": "Columbia", 
      "first_name": "Joanne", 
      "last_name": "Hafter", 
      "user_id": 225834, 
      "submission": "Will you pledge to change the current filibuster rule to what it had been in the past where a Senator had to stand and speak for the duration his/her filibuster? If not, why not?", 
      "district": "SC_02", 
      "created": "2013-08-09T01:33:01", 
      "state": "SC", 
      "iface": "timeline_vote", 
      "y": 34.0811, 
      "x": -81.1949, 
      "id": 16254716, 
      "question_id": "16197620"
    }, 
    {
      "city": "Henderson", 
      "first_name": "Ross", 
      "last_name": "Yates", 
      "user_id": 1627577, 
      "submission": "Would you support a living wage law that would force corporations, like Wal-Mart, whose Walton family owns more wealth than 40% of all Americans, to pay  living wages to all of their workers?", 
      "district": "NV_03", 
      "created": "2013-08-09T01:33:00", 
      "state": "NV", 
      "iface": "timeline_vote", 
      "y": 36.058, 
      "x": -114.96, 
      "id": 16254713, 
      "question_id": "16210264"
    }, 
    {
      "city": "Port Saint Lucie", 
      "first_name": "Mark", 
      "last_name": "Quigley", 
      "user_id": 713641, 
      "submission": "How will you support the dignity and freedom of women to make medical decisions with their health care providers without interference of federal and state laws?", 
      "district": "FL_18", 
      "created": "2013-08-09T01:33:00", 
      "state": "FL", 
      "iface": "timeline_vote", 
      "y": 27.2981, 
      "x": -80.2967, 
      "id": 16254714, 
      "question_id": "16183415"
    }, 
    {
      "city": "Manteca", 
      "first_name": "Fernando", 
      "last_name": "Valcarcel", 
      "user_id": 1685731, 
      "submission": "To all Candidates...Will you support Elizabeth Warren's bill to allow college students to borrow under 1% interest of college loans? ", 
      "district": "CA_10", 
      "created": "2013-08-09T01:32:55", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 37.8058, 
      "x": -121.221, 
      "id": 16254709, 
      "question_id": "16200733"
    }, 
    {
      "city": "Spring Lake", 
      "first_name": "Joshua", 
      "last_name": "Davis", 
      "user_id": 1696920, 
      "submission": "Would you sponsor a constitutional amendment affirming that constitutional rights are for people, not corporations, and that Congress and the states can limit political spending in elections?", 
      "district": "MI_02", 
      "created": "2013-08-09T01:32:53", 
      "state": "MI", 
      "iface": "timeline_vote", 
      "y": 43.0865, 
      "x": -86.1893, 
      "id": 16254707, 
      "question_id": "16180998"
    }, 
    {
      "city": "Mart", 
      "first_name": "Alice", 
      "last_name": "Mechler", 
      "user_id": 729643, 
      "submission": "What would you do to help assure that women's health issues, including the right to birth control and abortion, are not undermined for any American woman?", 
      "district": "TX_17", 
      "created": "2013-08-09T01:32:46", 
      "state": "TX", 
      "iface": "timeline_vote", 
      "y": 31.5481, 
      "x": -96.8375, 
      "id": 16254705, 
      "question_id": "16175230"
    }, 
    {
      "city": "King", 
      "first_name": "Nancy", 
      "last_name": "Brown", 
      "user_id": 1806913, 
      "submission": "will you pledge to oppose Any cuts to social Security or Medicare?", 
      "district": "NC_06", 
      "created": "2013-08-09T01:32:37", 
      "state": "NC", 
      "iface": "timeline_vote", 
      "y": 36.2873, 
      "x": -80.3562, 
      "id": 16254695, 
      "question_id": "16185364"
    }, 
    {
      "city": "Roslindale", 
      "first_name": "Margaret", 
      "last_name": "Kelner", 
      "user_id": 1644559, 
      "submission": "To all Candidates...Will you support Elizabeth Warren's bill to allow college students to borrow under 1% interest of college loans? ", 
      "district": "MA_07", 
      "created": "2013-08-09T01:32:29", 
      "state": "MA", 
      "iface": "timeline_vote", 
      "y": 42.2847, 
      "x": -71.1277, 
      "id": 16254684, 
      "question_id": "16200733"
    }, 
    {
      "city": "Morgantown", 
      "first_name": "Harper", 
      "last_name": "Grimm", 
      "user_id": 455804, 
      "submission": "What are your thoughts on how to stop corporate welfare, tax loopholes and subsidies.", 
      "district": "WV_01", 
      "created": "2013-08-09T01:32:29", 
      "state": "WV", 
      "iface": "timeline_vote", 
      "y": 39.6365, 
      "x": -79.9511, 
      "id": 16254685, 
      "question_id": "16206470"
    }, 
    {
      "city": "San Bruno", 
      "first_name": "Robert", 
      "last_name": "Casillas", 
      "user_id": 1777557, 
      "submission": "We believe that all Americans should have the same health care package.  Why do members of Congress have a health care package that the rest of us do not enjoy?", 
      "district": "CA_14", 
      "created": "2013-08-09T01:32:28", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 37.625, 
      "x": -122.432, 
      "id": 16254681, 
      "question_id": "16173335"
    }, 
    {
      "city": "Flushing", 
      "first_name": "Teri", 
      "last_name": "Schlesinger", 
      "user_id": 388641, 
      "submission": "What will you do to stop fracking for natural gas, and all fossil fuel drilling for that matter, and move us to a clean energy economy?", 
      "district": "NY_06", 
      "created": "2013-08-09T01:32:27", 
      "state": "NY", 
      "iface": "timeline_vote", 
      "y": 40.7702, 
      "x": -73.826, 
      "id": 16254679, 
      "question_id": "16172281"
    }, 
    {
      "city": "Columbia", 
      "first_name": "Jeffrey", 
      "last_name": "Powers", 
      "user_id": 1664835, 
      "submission": "What priority will you give to  issues that truly impact the working poor - like affordable housing for renters, affordable quality childcare and public transportation?", 
      "district": "MD_07", 
      "created": "2013-08-09T01:32:26", 
      "state": "MD", 
      "iface": "timeline_vote", 
      "y": 39.213, 
      "x": -76.8823, 
      "id": 16254678, 
      "question_id": "16175274"
    }, 
    {
      "city": "Vancouver", 
      "first_name": "ROSE MARIE", 
      "last_name": "HARSHMAN", 
      "user_id": 1703556, 
      "submission": "will you pledge to oppose Any cuts to social Security or Medicare?", 
      "district": "WA_03", 
      "created": "2013-08-09T01:32:16", 
      "state": "WA", 
      "iface": "timeline_vote", 
      "y": 45.6713, 
      "x": -122.56, 
      "id": 16254666, 
      "question_id": "16185364"
    }, 
    {
      "city": "Hesperia", 
      "first_name": "Elinor", 
      "last_name": "Vega", 
      "user_id": 596366, 
      "submission": "What are you doing to ensure that all residents have access to a living wage and to help create jobs for those still looking for work, five years after the Great Recession and the weak recovery?", 
      "district": "CA_08", 
      "created": "2013-08-09T01:32:08", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 34.4165, 
      "x": -117.307, 
      "id": 16254652, 
      "question_id": "16201159"
    }, 
    {
      "city": "Pompton Lakes", 
      "first_name": "Donald", 
      "last_name": "Cataruozolo", 
      "user_id": 1806717, 
      "submission": "What are you doing to ensure that all residents have access to a living wage and to help create jobs for those still looking for work, five years after the Great Recession and the weak recovery?", 
      "district": "NJ_11", 
      "created": "2013-08-09T01:32:08", 
      "state": "NJ", 
      "iface": "timeline_vote", 
      "y": 41.0005, 
      "x": -74.2869, 
      "id": 16254654, 
      "question_id": "16201159"
    }
  ]
});
