opendebate.processTimeline({
  "iface": "timeline", 
  "entries": [
    {
      "city": "portland", 
      "first_name": "khabira", 
      "last_name": "mcdow-keefer", 
      "user_id": 1245402, 
      "submission": "Would you take on the previously untouchable topic of rampant corporate lobbying causing unfair decisions tantamount to political bribery?", 
      "district": "OR_01", 
      "created": "2013-08-09T03:56:03", 
      "state": "OR", 
      "iface": "timeline_vote", 
      "y": 45.6334, 
      "x": -122.856, 
      "id": 16260968, 
      "question_id": "16190319"
    }, 
    {
      "city": "Knoxville", 
      "first_name": "John", 
      "last_name": "Kernodle", 
      "user_id": 843530, 
      "submission": "Will you oppose your party's President and demand an immediate end to the war in Afghanistan, drone attacks and NSA spying on us in the name of \"national security\"?", 
      "district": "TN_02", 
      "created": "2013-08-09T03:56:02", 
      "state": "TN", 
      "iface": "timeline_vote", 
      "y": 35.8564, 
      "x": -84.1283, 
      "id": 16260967, 
      "question_id": "16210626"
    }, 
    {
      "city": "Rockville", 
      "first_name": "Gary", 
      "last_name": "Brown", 
      "user_id": 1809156, 
      "submission": "Why is Social Security referred to by many elected Representatives and Senators in Washington as an \"entitlement\" when, first, we all pay or paid into it during all of our working years, and second, by law, normal tax revenue can not be used to fund It?  Is it because the government has used up all the money paid into Social Security over the years, and so that now the government has to raise more money to pay Social Security's current obligations?", 
      "district": "MD_06", 
      "created": "2013-08-09T03:56:01", 
      "state": "MD", 
      "iface": "timeline_vote", 
      "y": 39.0962, 
      "x": -77.0955, 
      "id": 16260966, 
      "question_id": "16180456"
    }, 
    {
      "city": "Lees Summit", 
      "first_name": "Mayzella", 
      "last_name": "White-Boyd", 
      "user_id": 1806576, 
      "submission": "What would you do to end the SCOTUS ruling Citizens United & how will you stop the GOP led states enacting extremist voter suppresion?", 
      "district": "MO_06", 
      "created": "2013-08-09T03:55:58", 
      "state": "MO", 
      "iface": "timeline_vote", 
      "y": 38.9192, 
      "x": -94.3208, 
      "id": 16260965, 
      "question_id": "16207073"
    }, 
    {
      "city": "Brooklyn", 
      "first_name": "Randi", 
      "last_name": "Ross", 
      "user_id": 347199, 
      "submission": "What are your thoughts on how to stop corporate welfare, tax loopholes and subsidies.", 
      "district": "NY_08", 
      "created": "2013-08-09T03:55:52", 
      "state": "NY", 
      "iface": "timeline_vote", 
      "y": 40.5774, 
      "x": -73.9945, 
      "id": 16260963, 
      "question_id": "16206470"
    }, 
    {
      "city": "Newport", 
      "first_name": "Gayle", 
      "last_name": "Sprague", 
      "user_id": 1750016, 
      "submission": "The threat that hangs over the country today is a GOP determined to destroy the middle class and the values that define it.  What specific steps will you recommend to confront, not appease, the GOP?", 
      "district": "KY_04", 
      "created": "2013-08-09T03:55:52", 
      "state": "KY", 
      "iface": "timeline_vote", 
      "y": 39.0202, 
      "x": -84.4402, 
      "id": 16260964, 
      "question_id": "16172694"
    }, 
    {
      "city": "Apache Junction", 
      "first_name": "Jeanette", 
      "last_name": "Edwards", 
      "user_id": 905060, 
      "submission": "Will you pledge to oppose cuts to Social Security and Medicare benefits (and sign on to expand these programs)?", 
      "district": "AZ_04", 
      "created": "2013-08-09T03:55:42", 
      "state": "AZ", 
      "iface": "timeline_vote", 
      "y": 33.4124, 
      "x": -111.59, 
      "id": 16260958, 
      "question_id": "16221486"
    }, 
    {
      "city": "Elgin", 
      "first_name": "Marilee", 
      "last_name": "Urban", 
      "user_id": 1108033, 
      "submission": "What is your position on the challenges facing public schools created by corporate-backed education reform, such as the unchecked proliferation of charter schools, the rampant use and misuse of standardized testing, and the erosion of collective bargaining rights for teachers?", 
      "district": "OR_02", 
      "created": "2013-08-09T03:55:37", 
      "state": "OR", 
      "iface": "timeline_vote", 
      "y": 45.5917, 
      "x": -117.894, 
      "id": 16260955, 
      "question_id": "16196860"
    }, 
    {
      "city": "Fort Worth", 
      "first_name": "Jackie", 
      "last_name": "VanBrocklin", 
      "user_id": 1157271, 
      "submission": "why does Congress feel they deserve more then the constituents they represent?", 
      "district": "TX_12", 
      "created": "2013-08-09T03:55:33", 
      "state": "TX", 
      "iface": "timeline_vote", 
      "y": 32.7433, 
      "x": -97.3805, 
      "id": 16260949, 
      "question_id": "16184213"
    }, 
    {
      "city": "Beaverton", 
      "first_name": "Deborah", 
      "last_name": "Averill", 
      "user_id": 577766, 
      "submission": "Plutocracy is Government by the Wealthy. What will you do to reduce or eliminate control of government by the wealthy?", 
      "district": "OR_01", 
      "created": "2013-08-09T03:55:10", 
      "state": "OR", 
      "iface": "timeline_vote", 
      "y": 45.4583, 
      "x": -122.797, 
      "id": 16260937, 
      "question_id": "16175500"
    }, 
    {
      "city": "Portland", 
      "first_name": "michael", 
      "last_name": "velasquez", 
      "user_id": 675735, 
      "submission": "Do you intend to be a vocal advocate favoring mandatory labeling of food and beverage products that contain genetically modified ingredients...labeling that indicates the presence of GMO?", 
      "district": "OR_03", 
      "created": "2013-08-09T03:54:53", 
      "state": "OR", 
      "iface": "timeline_vote", 
      "y": 45.4826, 
      "x": -122.637, 
      "id": 16260927, 
      "question_id": "16248162"
    }, 
    {
      "city": "Eugene", 
      "first_name": "Patience", 
      "last_name": "Pontious", 
      "user_id": 1808482, 
      "submission": "I was surprised and dimayed you supported the Monsanto Farm Bill. Do you support a communities right to require GMO labeling and to prohibit GMO crops from being planted within pollinating distance of  established Organic Farms?", 
      "district": "OR_04", 
      "created": "2013-08-09T03:54:40", 
      "state": "OR", 
      "iface": "timeline_vote", 
      "y": 43.9495, 
      "x": -123.128, 
      "id": 16260920, 
      "question_id": "16174618"
    }, 
    {
      "city": "Bremerton", 
      "first_name": "Rich", 
      "last_name": "S", 
      "user_id": 1774424, 
      "submission": "The big banks want to innovate.  Will you demand that banks get approval from federal regulators BEFORE they implement high risk innovations like Credit Default Swaps and Collateralized Obligations?", 
      "district": "WA_06", 
      "created": "2013-08-09T03:54:02", 
      "state_votes": 0, 
      "votes": 1, 
      "district_votes": 0, 
      "state": "WA", 
      "iface": "timeline_question", 
      "y": 47.5746, 
      "x": -122.811, 
      "latest_vote": "2013-08-09T03:55:35", 
      "id": 16260903, 
      "trending_score": 1.5
    }, 
    {
      "city": "Missoula", 
      "first_name": "dorothy", 
      "last_name": "gates", 
      "user_id": 1750631, 
      "submission": "Where do you stand on overturning Citizens United with a Constitutional Amendment such as the one proposed by MoveToAmend.org", 
      "district": "MT_01", 
      "created": "2013-08-09T03:54:02", 
      "state": "MT", 
      "iface": "timeline_vote", 
      "y": 46.8587, 
      "x": -114.04, 
      "id": 16260902, 
      "question_id": "16172777"
    }, 
    {
      "city": "Jacksonville", 
      "first_name": "Barbara", 
      "last_name": "Martin", 
      "user_id": 1008922, 
      "submission": "Citizens For Tax Justice reports that corporate taxes are at their lowest level since 1931 (the Hoover years).Will you fight against the unprecedented tax evasion of large American firms?", 
      "district": "TX_05", 
      "created": "2013-08-09T03:53:01", 
      "state": "TX", 
      "iface": "timeline_vote", 
      "y": 31.9501, 
      "x": -95.2575, 
      "id": 16260871, 
      "question_id": "16173210"
    }, 
    {
      "city": "Louisville", 
      "first_name": "Anthony", 
      "last_name": "Hamilton", 
      "user_id": 169533, 
      "submission": "What will you do about gun control and the scare tactics/bullying by the NRA and gun lobbyists?  How will you approach the Right's program of 'divisiveness and culture of fear' that now rips us apart?", 
      "district": "KY_03", 
      "created": "2013-08-09T03:52:23", 
      "state": "KY", 
      "iface": "timeline_vote", 
      "y": 38.248, 
      "x": -85.7646, 
      "id": 16260846, 
      "question_id": "16176673"
    }, 
    {
      "city": "San Jose", 
      "first_name": "S. Kathleen", 
      "last_name": "Martin", 
      "user_id": 1183556, 
      "submission": "What would you do to end the SCOTUS ruling Citizens United & how will you stop the GOP led states enacting extremist voter suppresion?", 
      "district": "CA_18", 
      "created": "2013-08-09T03:51:41", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 37.3136, 
      "x": -121.931, 
      "id": 16260826, 
      "question_id": "16207073"
    }, 
    {
      "city": "Myrtle Beach", 
      "first_name": "Daniel", 
      "last_name": "Wilder", 
      "user_id": 1648696, 
      "submission": "What will you do to overturn Citizen's United?", 
      "district": "SC_07", 
      "created": "2013-08-09T03:51:34", 
      "state": "SC", 
      "iface": "timeline_vote", 
      "y": 33.655, 
      "x": -78.9453, 
      "id": 16260821, 
      "question_id": "16172765"
    }, 
    {
      "city": "Los Angeles", 
      "first_name": "Tonnie", 
      "last_name": "Katz", 
      "user_id": 1147770, 
      "submission": "Why is Social Security referred to by many elected Representatives and Senators in Washington as an \"entitlement\" when, first, we all pay or paid into it during all of our working years, and second, by law, normal tax revenue can not be used to fund It?  Is it because the government has used up all the money paid into Social Security over the years, and so that now the government has to raise more money to pay Social Security's current obligations?", 
      "district": "CA_33", 
      "created": "2013-08-09T03:50:23", 
      "state": "CA", 
      "iface": "timeline_vote", 
      "y": 34.0677, 
      "x": -118.351, 
      "id": 16260791, 
      "question_id": "16180456"
    }, 
    {
      "city": "Crowley", 
      "first_name": "JALEEN", 
      "last_name": "REYNOLDS", 
      "user_id": 393302, 
      "submission": "Would you support Medicare paying for dental care?", 
      "district": "TX_06", 
      "created": "2013-08-09T03:50:02", 
      "state": "TX", 
      "iface": "timeline_vote", 
      "y": 32.5847, 
      "x": -97.372, 
      "id": 16260784, 
      "question_id": "16174466"
    }
  ]
});
