opendebate.processTimeline({
  "iface": "timeline", 
  "entries": [
    {
      "city": "Nashville", 
      "first_name": "D. S.", 
      "last_name": "Kinzie", 
      "user_id": 88880, 
      "submission": "How will you support the dignity and freedom of women to make medical decisions with their health care providers without interference of federal and state laws?", 
      "district": "TN_05", 
      "created": "2013-08-09T10:29:01", 
      "state": "TN", 
      "iface": "timeline_vote", 
      "y": 36.1088, 
      "x": -86.7806, 
      "id": 16270890, 
      "question_id": "16183415"
    }, 
    {
      "city": "Newton", 
      "first_name": "Eric", 
      "last_name": "Chipman", 
      "user_id": 133784, 
      "submission": "What will you do to curb the influence of lobbyist and limit campaign spending.  ", 
      "district": "MA_04", 
      "created": "2013-08-09T10:28:29", 
      "state": "MA", 
      "iface": "timeline_vote", 
      "y": 42.3525, 
      "x": -71.1907, 
      "id": 16270885, 
      "question_id": "16201563"
    }, 
    {
      "city": "Raleigh", 
      "first_name": "John", 
      "last_name": "Wilson", 
      "user_id": 64411, 
      "submission": "What will you do to ensure that all Americans have access to the voting booth and what will you do to get money out of our elections so that we all have an equal voice?", 
      "district": "NC_04", 
      "created": "2013-08-09T10:27:32", 
      "state": "NC", 
      "iface": "timeline_vote", 
      "y": 35.7927, 
      "x": -78.6911, 
      "id": 16270873, 
      "question_id": "16205834"
    }, 
    {
      "city": "Golden", 
      "first_name": "LouAnne", 
      "last_name": "Dale", 
      "user_id": 91258, 
      "submission": "Are you in favor of and would you propose a move for and make  an effort in PURSUING  Congress  to return  WITH INTEREST DUE TO THE LAST PENNEY all  they  \"borrowed\"  from  Social Security without the people's consent.", 
      "district": "CO_07", 
      "created": "2013-08-09T10:26:51", 
      "state": "CO", 
      "iface": "timeline_vote", 
      "y": 39.818, 
      "x": -105.251, 
      "id": 16270869, 
      "question_id": "16208136"
    }, 
    {
      "city": "Rockport", 
      "first_name": "Lois", 
      "last_name": "Brynes", 
      "user_id": 49354, 
      "submission": "Do you understand the serious threat of climate disruption and will you work hard to fend off global warming?", 
      "district": "MA_06", 
      "created": "2013-08-09T10:26:03", 
      "state": "MA", 
      "iface": "timeline_vote", 
      "y": 42.6587, 
      "x": -70.6187, 
      "id": 16270861, 
      "question_id": "16172303"
    }, 
    {
      "city": "Seattle", 
      "first_name": "john", 
      "last_name": "guros", 
      "user_id": 1707018, 
      "submission": "Why is it that Halliburton only gets a $200K fine for destroying evidence concerning the Gulf oil spill when if you make a copy of a DVD you get a $250K fine and up to 5 years in prison?", 
      "district": "WA_09", 
      "created": "2013-08-09T10:19:57", 
      "state": "WA", 
      "iface": "timeline_vote", 
      "y": 47.4051, 
      "x": -122.31, 
      "id": 16270809, 
      "question_id": "16175493"
    }, 
    {
      "city": "Darien", 
      "first_name": "Marc", 
      "last_name": "Friedman", 
      "user_id": 1060885, 
      "submission": "Will you protect Social Security And Medicare by not cutting it with the chained CPI for Social Security that has been mentioned.  Also, no cuts to Medicare but closing the donute hole 100% so seniors aren't left fending for themselves to pay full price for their drugs.", 
      "district": "IL_11", 
      "created": "2013-08-09T10:19:04", 
      "state": "IL", 
      "iface": "timeline_vote", 
      "y": 41.7499, 
      "x": -87.977, 
      "id": 16270800, 
      "question_id": "16175570"
    }, 
    {
      "city": "Chelmsford", 
      "first_name": "faith", 
      "last_name": "vigeant", 
      "user_id": 1090614, 
      "submission": "Do/would you support an investigation of any/all Representative\u2019s that signed the Norquist pledge as having a conflict of interest with their pledge to uphold the Constitution and make government work?", 
      "district": "MA_03", 
      "created": "2013-08-09T10:17:47", 
      "state": "MA", 
      "iface": "timeline_vote", 
      "y": 42.6233, 
      "x": -71.3647, 
      "id": 16270781, 
      "question_id": "16206139"
    }, 
    {
      "city": "Thomasboro", 
      "first_name": "Wanda", 
      "last_name": "Schideman", 
      "user_id": 1678833, 
      "submission": "What will you do to ensure that all Americans have access to the voting booth and what will you do to get money out of our elections so that we all have an equal voice?", 
      "district": "IL_15", 
      "created": "2013-08-09T10:14:08", 
      "state": "IL", 
      "iface": "timeline_vote", 
      "y": 40.243, 
      "x": -88.1815, 
      "id": 16270717, 
      "question_id": "16205834"
    }, 
    {
      "city": "Clayton", 
      "first_name": "Vicki", 
      "last_name": "Thompson", 
      "user_id": 1796286, 
      "submission": "Will you make repairing and updating the infrastructure, not just roads but bridges and the electrical grid, a priority?", 
      "district": "NC_07", 
      "created": "2013-08-09T10:12:34", 
      "state": "NC", 
      "iface": "timeline_vote", 
      "y": 35.6363, 
      "x": -78.4448, 
      "id": 16270682, 
      "question_id": "16191114"
    }, 
    {
      "city": "Belleville", 
      "first_name": "George", 
      "last_name": "Bourlotos", 
      "user_id": 1679065, 
      "submission": "Plutocracy is Government by the Wealthy. What will you do to reduce or eliminate control of government by the wealthy?", 
      "district": "NJ_08", 
      "created": "2013-08-09T10:09:28", 
      "state": "NJ", 
      "iface": "timeline_vote", 
      "y": 40.7937, 
      "x": -74.1649, 
      "id": 16270644, 
      "question_id": "16175500"
    }, 
    {
      "city": "Nashville", 
      "first_name": "Ian", 
      "last_name": "Salter", 
      "user_id": 203405, 
      "submission": "Will you work to support Elizabeth Warren's efforts to revise Glass-Steagall", 
      "district": "TN_05", 
      "created": "2013-08-09T10:08:09", 
      "state": "TN", 
      "iface": "timeline_vote", 
      "y": 36.1806, 
      "x": -86.7355, 
      "id": 16270624, 
      "question_id": "16265543"
    }, 
    {
      "city": "New York", 
      "first_name": "Nadine", 
      "last_name": "Laguardia", 
      "user_id": 1215424, 
      "submission": "Who are your corporate sponsors? Would you be in favor of all politicians wearing patches on their cloths with the corporate logo's of their sponsors just like athletes do. This way we know where the money comes from before we vote.", 
      "district": "NY_10", 
      "created": "2013-08-09T10:05:43", 
      "state": "NY", 
      "iface": "timeline_vote", 
      "y": 40.7996, 
      "x": -73.9703, 
      "id": 16270596, 
      "question_id": "16175691"
    }, 
    {
      "city": "Lincoln", 
      "first_name": "Jenny", 
      "last_name": "Golay", 
      "user_id": 194531, 
      "submission": "Will you pledge to oppose cuts to Social Security and Medicare benefits (and sign on to expand these programs)?", 
      "district": "MA_05", 
      "created": "2013-08-09T09:59:37", 
      "state": "MA", 
      "iface": "timeline_vote", 
      "y": 42.4239, 
      "x": -71.3142, 
      "id": 16270530, 
      "question_id": "16172266"
    }, 
    {
      "city": "Clermont", 
      "first_name": "Hector", 
      "last_name": "Allen", 
      "user_id": 1809540, 
      "submission": "Will you fight to protect the Clean Air Act, the Clean Water Act and the EPA in a House of Representatives that has become increasingly hostile to all three?", 
      "district": "FL_10", 
      "created": "2013-08-09T09:58:13", 
      "state": "FL", 
      "iface": "timeline_vote", 
      "y": 28.5359, 
      "x": -81.7638, 
      "id": 16270521, 
      "question_id": "16226952"
    }, 
    {
      "city": "Alexandria", 
      "first_name": "John", 
      "last_name": "Grim", 
      "user_id": 785415, 
      "submission": "Because of the Financial disaster caused by deregulation during the Bush years, will you support a rebirth of the New 21st Century Glass/Steagall Act and why?", 
      "district": "VA_08", 
      "created": "2013-08-09T09:58:02", 
      "state": "VA", 
      "iface": "timeline_vote", 
      "y": 38.783, 
      "x": -77.12, 
      "id": 16270518, 
      "question_id": "16173264"
    }, 
    {
      "city": "North Las Vegas", 
      "first_name": "Bernhard", 
      "last_name": "Lambert", 
      "user_id": 392784, 
      "submission": "The threat that hangs over the country today is a GOP determined to destroy the middle class and the values that define it.  What specific steps will you recommend to confront, not appease, the GOP?", 
      "district": "NV_04", 
      "created": "2013-08-09T09:55:35", 
      "state": "NV", 
      "iface": "timeline_vote", 
      "y": 36.2577, 
      "x": -115.142, 
      "id": 16270473, 
      "question_id": "16172694"
    }, 
    {
      "city": "Tampa", 
      "first_name": "DeRoy", 
      "last_name": "Nunoo", 
      "user_id": 702305, 
      "submission": "will you pledge to oppose Any cuts to social Security or Medicare?", 
      "district": "FL_15", 
      "created": "2013-08-09T09:52:55", 
      "state": "FL", 
      "iface": "timeline_vote", 
      "y": 28.1145, 
      "x": -82.3639, 
      "id": 16270440, 
      "question_id": "16185364"
    }, 
    {
      "city": "Eugene", 
      "first_name": "Patience", 
      "last_name": "Pontious", 
      "user_id": 1808482, 
      "submission": "Would you be willing to be polygraphed while answering these questions?", 
      "district": "OR_04", 
      "created": "2013-08-09T09:48:50", 
      "state_votes": 0, 
      "votes": 0, 
      "district_votes": 0, 
      "state": "OR", 
      "iface": "timeline_question", 
      "y": 43.9495, 
      "x": -123.128, 
      "latest_vote": null, 
      "id": 16270415, 
      "trending_score": 0.5
    }, 
    {
      "city": "New Bedford", 
      "first_name": "alan", 
      "last_name": "mc alister", 
      "user_id": 636564, 
      "submission": "Will you pledge to oppose cuts to Social Security and Medicare benefits (and sign on to expand these programs)?", 
      "district": "MA_09", 
      "created": "2013-08-09T09:46:55", 
      "state": "MA", 
      "iface": "timeline_vote", 
      "y": 41.6634, 
      "x": -70.9362, 
      "id": 16270409, 
      "question_id": "16172266"
    }
  ]
});
